name: nivo_plugins
description: First-party CGM plugins and authoring tools for Nivo.
publish_to: none
version: 1.0.1-beta.1

environment:
  sdk: ^3.12.0

dependencies:
  path: ^1.9.1

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
  args: ^2.7.0
  crypto: ^3.0.6
